version: "3"
output: prefixed

tasks:
  check:clang-format:
    desc: "Check - clang-format"
    cmds:
      - clang-format -n -Werror --verbose $(git ls-files | grep -E
        '\.hpp$|\.cpp$')
  check:shellcheck:
    desc: "Check - shellcheck"
    cmds:
      - shellcheck $(git ls-files | grep '\.sh$')
  check:yarn:dedupe:
    desc: "Check - yarn dedupe"
    cmds:
      - yarn run check:yarn:dedupe
    deps:
      - install:yarn
  check:
    desc: "All checks"
    deps:
      - check:clang-format
      - check:shellcheck
      - check:yarn:dedupe

  install:yarn:
    desc: "Install - yarn"
    run: once
    sources:
      - package.json
      - yarn.lock
    cmds:
      - yarn
  install:
    desc: "Install all dependencies"
    deps:
      - install:yarn

  all:
    desc: "All tasks"
    aliases:
      - default
    deps:
      - check
