version: "3"

tasks:
  check:clang-format:
    desc: "Check - clang-format"
    cmds:
      - clang-format -n -Werror --verbose $(git ls-files | grep -E
        '\.hpp$|\.cpp$')
  check:github-actions:
    desc: "Check - Github actions"
    cmds:
      - npm run check:github-actions
  check:npm:dedupe:
    desc: "Check - npm dedupe"
    cmds:
      - npm run check:npm:dedupe
  check:prettier:
    desc: "Check - prettier"
    cmds:
      - npm run check:prettier
  check:renovateconfig:
    desc: "Check - Renovate config"
    cmds:
      - npm run check:renovateconfig
  check:
    desc: "All checks"
    deps:
      - check:clang-format
      - check:github-actions
      - check:prettier
      - check:renovateconfig

  fix:format:prettier:
    desc: "Fix - prettier"
    cmds:
      - npm run fix:prettier

  fix:format:
    desc: "All fixes"
    deps:
      - fix:format:prettier

  fix:
    desc: "All fixes"
    deps:
      - fix:format

  all:
    desc: "All tasks"
    aliases:
      - default
    deps:
      - check
