version: "3"

tasks:
  check:clang-format:
    desc: "Check - clang-format"
    cmds:
      - clang-format -n -Werror --verbose $(git ls-files | grep -E
        '\.hpp$|\.cpp$')
  check:github-actions:
    desc: "Check - Github actions"
    cmds:
      - yarn run check:github-actions
  check:prettier:
    desc: "Check - prettier"
    cmds:
      - yarn run check:prettier
  check:renovateconfig:
    desc: "Check - Renovate config"
    cmds:
      - yarn run check:renovateconfig
  check:yarn:dedupe:
    desc: "Check - yarn dedupe"
    cmds:
      - yarn run check:yarn:dedupe
  check:
    desc: "All checks"
    deps:
      - check:clang-format
      - check:github-actions
      - check:prettier
      - check:renovateconfig
      - check:yarn:dedupe

  fix:format:prettier:
    desc: "Fix - prettier"
    cmds:
      - yarn run fix:prettier

  fix:format:
    desc: "All fixes"
    deps:
      - fix:format:prettier

  fix:
    desc: "All fixes"
    deps:
      - fix:format

  all:
    desc: "All tasks"
    aliases:
      - default
    deps:
      - check
