name: CMake project setup
description: Setup cmake, vcpkg and CMakeUserPresets.json

runs:
  using: composite
  steps:
    - name: Install CMake
      uses: lukka/get-cmake@5979409e62bdf841487c5fb3c053149de97a86d3 # v3.31.2
    - name: Setup anew (or from cache) vcpkg (and does not build any package)
      uses: lukka/run-vcpkg@5e0cab206a5ea620130caf672fce3e4a6b5666a1 # v11.5
    - name: Prepare CMakeUserPresets.json
      run: cp .github/CMakeUserPresets.json CMakeUserPresets.json
      shell: bash
