name: CMake project setup
description: Setup cmake, vcpkg and CMakeUserPresets.json
inputs:
  conanProfileHost:
    description: Conan host profile to use for installing dependencies
    required: false
    default: "default"

runs:
  using: composite
  steps:
    - name: Install CMake
      uses: lukka/get-cmake@57c20a23a6cac5b90f31864439996e5b206df9dc # v4.0.1
    - name: Setup Conan Client
      id: setup-conan
      uses: conan-io/setup-conan@593e0b5bf725f7a0fbf8ba6c249c78e09141cd85 # v1.0.0
      with:
        cache_packages: true
    - name: Prepare Conan profiles - non-windows
      if: runner.os != 'Windows'
      run: |
        cp .github/conan-profiles/* ${{steps.setup-conan.outputs.conan-home}}/profiles/
        conan profile list
      shell: bash
    - name: Prepare Conan profiles - windows
      if: runner.os == 'Windows'
      run: |
        powershell Copy-Item .github\conan-profiles\* ${{steps.setup-conan.outputs.conan-home}}\profiles\
        conan profile list
      shell: pwsh
    - name: Prepare CMakeUserPresets.json
      run: cp .github/CMakeUserPresets.json CMakeUserPresets.json
      shell: bash
    - name: Conan install
      run: |
        conan install . \
          --build=missing \
          -pr:h ${{inputs.conanProfileHost}} \
          -c:h tools.cmake.cmaketoolchain:user_presets="CMakeConanPresets.json"
      shell: bash
