name: CMake project setup
description: Setup cmake, conan and CMakeUserPresets.json

runs:
  using: composite
  steps:
    - name: Install CMake
      uses: lukka/get-cmake@6b3e96a9bc9976b8b546346fdd102effedae0ca8 # v4.0.3
    - name: Setup Conan Client
      id: setup-conan
      uses: conan-io/setup-conan@09566912d661de90608308897a4d513e850c04e8 # v1.2.0
      with:
        cache_packages: true
    - name: Prepare CMakeUserPresets.json
      run: cp .github/CMakeUserPresets.json CMakeUserPresets.json
      shell: bash
