name: yarn project setup
description: Setup node, yarn and tools for project
runs:
  using: composite
  steps:
    - name: Enable corepack to install yarn
      run: corepack enable
      shell: bash
    - name: Setup node
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
      with:
        node-version: 22
        cache: yarn
    - name: Install yarn dev tools
      run: yarn install --immutable
      shell: bash
