name: yarn project setup
description: Setup node, yarn and tools for project
runs:
  using: composite
  steps:
    - name: Enable corepack to install yarn
      run: corepack enable
      shell: bash
    - name: Setup node
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
      with:
        node-version-file: package.json
        cache: yarn
    - name: Install yarn dev tools
      run: yarn install --immutable
      shell: bash
