FROM mcr.microsoft.com/devcontainers/base:alpine

RUN apk add --no-cache clang17
RUN apk add --no-cache clang17-dev
RUN apk add --no-cache libc++
RUN apk add --no-cache libc++-dev
RUN apk add --no-cache cmake
RUN apk add --no-cache gcc
RUN apk add --no-cache g++
RUN apk add --no-cache poetry
RUN apk add --no-cache python3
RUN apk add --no-cache samurai
RUN apk add --no-cache shellcheck
