version: '3'

includes:
  root:
    taskfile: ../taskfile.dist.yaml
    dir: ../

output: group

tasks:
  install:all:
    description: Install dependencies for all profiles supported in devcontainer
    deps:
      - task: root:install:conan
        vars:
          PROFILE: dev-gcc
          BUILD_TYPE: Debug
      - task: root:install:conan
        vars:
          PROFILE: dev-gcc
          BUILD_TYPE: Release
      - task: root:install:conan
        vars:
          PROFILE: dev-clang
          BUILD_TYPE: Debug
      - task: root:install:conan
        vars:
          PROFILE: dev-clang
          BUILD_TYPE: Release
