name: Build, test and run
on:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build-test-run:
    strategy:
      matrix:
        include:
          # MSVC
          - name: MSVC Debug
            os: windows-2025
            workflowPreset: ci-msvc-debug
            aocBinPath: ""
          - name: MSVC Release
            os: windows-2025
            workflowPreset: ci-msvc-release
            aocBinPath: build/aoc/aoc/Release/aoc.exe

          # Clang on Linux
          - name: Linux Clang Release
            os: ubuntu-24.04
            workflowPreset: ci-clang-release
            aocBinPath: build/aoc/aoc/aoc
          - name: Linux Clang Debug
            os: ubuntu-24.04
            workflowPreset: ci-clang-debug
            aocBinPath: build/aoc/aoc/aoc

          # Gcc 14 on Linux
          - name: Linux GCC 14 Release
            os: ubuntu-24.04
            workflowPreset: ci-gcc-14-release
            aocBinPath: build/aoc/aoc/aoc
          - name: Linux GCC 14 Debug
            os: ubuntu-24.04
            workflowPreset: ci-gcc-14-debug
            aocBinPath: build/aoc/aoc/aoc

    name: ${{matrix.name}} - Build + test + run
    runs-on: ${{matrix.os}}
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          submodules: true
      - name: Setup CMake project
        uses: ./.github/actions/cmake-project-setup
      - name: Run CMake workflow
        uses: lukka/run-cmake@af1be47fd7c933593f687731bc6fdbee024d3ff4 # v10.8
        with:
          workflowPreset: "${{matrix.workflowPreset}}"
      - name: Run aoc
        if: matrix.aocBinPath
        run: ./"${{matrix.aocBinPath}}"
