name: Build, test and run
on:
  push:
    branches: ["ci-enable-build-on-macos"]
  pull_request:
    paths:
      - "**.cpp"
      - "**.hpp"
      - "**/CMakeLists.txt"
      - ".github/actions/cmake-project-setup/**"
      - ".github/workflows/build-test-run.yaml"
      - ".github/CMakeUserPresets.json"
      - "aoc/**/input-*.txt"
      - "vcpkg-configuration.json"
      - "vcpkg.json"
  workflow_call:
  workflow_dispatch:

jobs:
  build-test-run:
    strategy:
      matrix:
        include:
          # MacOS 15
          - os: macos-15
            workflowPreset: ci-macos-debug

    name: ${{matrix.workflowPreset}} - Build + test + run
    runs-on: ${{matrix.os}}
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup CMake project
        uses: ./.github/actions/cmake-project-setup
      - name: Run CMake workflow
        uses: lukka/run-cmake@af1be47fd7c933593f687731bc6fdbee024d3ff4 # v10.8
        with:
          workflowPreset: "${{matrix.workflowPreset}}"
      - name: Run aoc
        if: matrix.aocBinPath
        run: ./"${{matrix.aocBinPath}}"

  inspect:
    name: Inspect
    runs-on: macos-15
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - run: |
          which c++ || true
          which -a c++ || true
          which clang++ || true
          which -a clang++ || true
          brew list
          brew list llvm@18 | sort || true
