name: Check - Shellcheck
on:
  pull_request:
    paths:
      - "**.sh"
      - ".github/workflows/check-shellcheck.yaml"
  workflow_dispatch:
permissions:
  contents: read

jobs:
  wf:
    uses: nikobockerman/github-workflows/.github/workflows/check-shellcheck.yaml@88efa388aef31b038ce87b84fa64378482af888c
