name: Check - clang-tidy
on:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  clang-tidy:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    strategy:
      matrix:
        include:
          - name: Clang Debug
            configurePreset: ci-clang-tidy-debug
          - name: Clang Release
            configurePreset: ci-clang-tidy-release
    name: ${{matrix.name}} - Clang tidy
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          submodules: true
      - name: Setup CMake project
        uses: ./.github/actions/cmake-project-setup
      - name: Configure CMake project
        uses: lukka/run-cmake@af1be47fd7c933593f687731bc6fdbee024d3ff4 # v10.8
        with:
          configurePreset: "${{matrix.configurePreset}}"
      - name: Run clang-tidy
        run: run-clang-tidy -p build
