name: Check - prettier

on:
  pull_request:
    paths-ignore:
      - "**.cpp"
      - "**.hpp"
  workflow_dispatch:

jobs:
  wf:
    uses: nikobockerman/github-workflows/.github/workflows/check-prettier.yaml@644da9d2d334bc8d06bcf57d735d7ca67040e818
