name: Check - Enforce all checks pass
on:
  pull_request:
permissions:
  checks: read

jobs:
  wf:
    uses: nikobockerman/github-workflows/.github/workflows/check-enforce-all-checks.yaml@f966254950c57f16c84f0f5a8f34728f50d19965
