name: Check - Enforce all checks pass
on:
  pull_request:
permissions:
  checks: read

jobs:
  wf:
    uses: nikobockerman/github-workflows/.github/workflows/check-enforce-all-checks.yaml@55864979db2fac18cce2945b11b50e5e06fea565
