name: Check - Devcontainer
on:
  pull_request:
    paths:
      - "**.cpp"
      - "**.hpp"
      - "**/CMakeLists.txt"
      - ".devcontainer/**"
      - ".github/conan-profiles/**"
      - ".github/workflows/check-devcontainer.yaml"
      - "aoc/**/input-*.txt"
      - "CMakePresets.json"
      - "conan.lock"
      - "conanfile.txt"
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  wf:
    uses: nikobockerman/github-workflows/.github/workflows/check-devcontainer.yaml@f966254950c57f16c84f0f5a8f34728f50d19965
    with:
      runCmd: |
        cmake --workflow --preset dev-clang-release && \
          ./build/clang/Release/aoc/aoc/aoc
