name: Check - Yarn and dependencies
on:
  pull_request:
    paths:
      - ".github/workflows/check-yarn.yaml"
      - "package.json"
      - "yarn.lock"
  workflow_dispatch:
permissions:
  contents: read

jobs:
  wf:
    uses: nikobockerman/github-workflows/.github/workflows/check-yarn.yaml@261e8683f0b52b7f6a9d91e2ea639a46f168ce8a
