name: Check - clang-tidy
on:
  pull_request:
    paths:
      - "**.cpp"
      - "**.hpp"
      - "**/CMakeLists.txt"
      - ".clang-tidy"
      - ".github/actions/cmake-project-setup/**"
      - ".github/conan-profiles/**"
      - ".github/workflows/check-clang-tidy.yaml"
      - ".github/CMakeUserPresets.json"
      - "CMakePresets.json"
      - "conan.lock"
      - "conanfile.txt"
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  clang-tidy:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    strategy:
      matrix:
        include:
          - name: Clang Debug
            conanProfileHost: ubuntu-clang-debug
            configurePreset: ci-clang-tidy-debug
            binaryDir: build/Debug
          - name: Clang Release
            conanProfileHost: ubuntu-clang-release
            configurePreset: ci-clang-tidy-release
            binaryDir: build/Release
    name: ${{matrix.name}} - Clang tidy
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup CMake project
        uses: ./.github/actions/cmake-project-setup
        with:
          conanProfileHost: ${{matrix.conanProfileHost}}
      - name: Configure CMake project
        uses: lukka/run-cmake@af1be47fd7c933593f687731bc6fdbee024d3ff4 # v10.8
        with:
          configurePreset: "${{matrix.configurePreset}}"
      - name: Run clang-tidy
        run: run-clang-tidy -p "${{matrix.binaryDir}}"
