name: Check - Renovate config
on:
  pull_request:
    paths:
      - ".github/renovate.json5"
      - ".github/workflows/check-renovate-config.yaml"
  workflow_dispatch:
permissions:
  contents: read

jobs:
  wf:
    uses: nikobockerman/github-workflows/.github/workflows/check-renovate-config.yaml@88efa388aef31b038ce87b84fa64378482af888c
