name: Check - prettier
on:
  pull_request:
    paths-ignore:
      - "**.cpp"
      - "**.hpp"
      - "conan.lock"
  workflow_dispatch:
permissions:
  contents: read

jobs:
  wf:
    uses: nikobockerman/github-workflows/.github/workflows/check-prettier.yaml@cc3e3fdec0b2379e550c1ea4059cb79f455ff668
