name: Check - Enforce all checks pass
on:
  pull_request:

jobs:
  wf:
    uses: nikobockerman/github-workflows/.github/workflows/check-enforce-all-checks.yaml@644da9d2d334bc8d06bcf57d735d7ca67040e818
    permissions:
      checks: read
