name: Check - prettier

on:
  pull_request:
    paths-ignore:
      - "**.cpp"
      - "**.hpp"
  workflow_dispatch:

jobs:
  wf:
    uses: nikobockerman/github-workflows/.github/workflows/check-prettier.yaml@18e084501edc3ba04f03f3dd40d7288765100e52
