name: Check - prettier

on:
  pull_request:
    paths-ignore:
      - "**.cpp"
      - "**.hpp"
  workflow_call:
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup npm tools
        uses: ./.github/actions/npm-tools-setup
      - name: Check prettier
        run: npm run check:prettier
