name: Check - Renovate config
on:
  pull_request:
    paths:
      - ".github/renovate.json5"
      - ".github/workflows/check-renovate-config.yaml"
  workflow_dispatch:

jobs:
  wf:
    uses: nikobockerman/github-workflows/.github/workflows/check-renovate-config.yaml@644da9d2d334bc8d06bcf57d735d7ca67040e818
