name: Check - clang-format
on:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  format:
    name: Validate formatting
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check with clang-format
        run: task check:clang-format
