name: Check - Yarn and dependencies
on:
  pull_request:
    paths:
      - ".github/workflows/check-yarn.yaml"
      - "package.json"
      - "yarn.lock"
  workflow_dispatch:
permissions:
  contents: read

jobs:
  wf:
    uses: nikobockerman/github-workflows/.github/workflows/check-yarn.yaml@f966254950c57f16c84f0f5a8f34728f50d19965
