name: Check - clang-format
on:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  format:
    name: Validate formatting
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
      - name: Check with clang-format
        run: task check:clang-format
