name: Check - prettier
on:
  pull_request:
    paths-ignore:
      - "**.cpp"
      - "**.hpp"
      - "conan.lock"
  workflow_dispatch:
permissions:
  contents: read

jobs:
  wf:
    uses: nikobockerman/github-workflows/.github/workflows/check-prettier.yaml@1d0ee1b00422598a785e5620925ce2ec0de2b6d3
