name: Check - Shellcheck
on:
  pull_request:
    paths:
      - "**.sh"
      - ".github/workflows/check-shellcheck.yaml"
  workflow_dispatch:
permissions:
  contents: read

jobs:
  wf:
    uses: nikobockerman/github-workflows/.github/workflows/check-shellcheck.yaml@a3ff11ed76f5e286d3a5e11ec6f6395ddbe6412d
