name: CI + CD
on:
  push:
    branches:
      - main
  schedule:
    # Run every Monday at 00:30 UTC
    - cron: "30 0 * * 1"
  workflow_dispatch:
permissions:
  contents: read
  packages: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
  deploy-devcontainer-cache:
    needs: ci
    uses: nikobockerman/github-workflows/.github/workflows/devcontainer-cache.yaml@55864979db2fac18cce2945b11b50e5e06fea565
    with:
      cache-type: final
