name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    # Run every Monday at 00:30 UTC
    - cron: "30 0 * * 1"

jobs:
  build-and-test:
    strategy:
      matrix:
        include:
          # MSVC
          - os: windows-latest
            workflowPreset: ci-msvc-debug
          - os: windows-latest
            workflowPreset: ci-msvc-release
          # Clang on Windows requires fix to
          # https://github.com/microsoft/vcpkg/issues/40912
          #- os: windows-latest
          #  workflowPreset: ClangWindows Debug
          #- os: windows-latest
          #  workflowPreset: ClangWindows Release
          # Clang on Linux
          - os: ubuntu-24.04
            workflowPreset: ci-clang-linux-debug
          - os: ubuntu-24.04
            workflowPreset: ci-clang-linux-release
          # Gcc 14 on Linux
          - os: ubuntu-24.04
            workflowPreset: ci-gcc-14-linux-debug
          # Gcc 14 Release build doesn't work with the
          # gcc 14.0.1 20240412 snapshot version available on Ubuntu Universe
          # The issue may be fixed in newer 14.1 or 14.2 versions.
          #- os: ubuntu-24.04
          #  workflowPreset: ci-gcc-14-linux-release

    name: ${{matrix.workflowPreset}}
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
      - name: Setup anew (or from cache) vcpkg (and does not build any package)
        uses: lukka/run-vcpkg@v11.5
      - name: Prepare presets
        run: cp .github/CMakeUserPresets.json CMakeUserPresets.json
        shell: bash
      - name:
          Run CMake consuming CMakePreset.json and run vcpkg to build packages
        uses: lukka/run-cmake@v10
        with:
          workflowPreset: "${{matrix.workflowPreset}}"
