name: CI

on:
  push:
    branches: ["ci-enable-clang-libcpp-on-linux"]
  workflow_dispatch:
  schedule:
    # Run every Monday at 00:30 UTC
    - cron: "30 0 * * 1"

jobs:
  build-and-test:
    strategy:
      matrix:
        include:
          # Clang with libc++ on Linux
          - os: ubuntu-24.04
            workflowPreset: ci-clang-libcpp-linux-debug
            aptPackages: libc++-dev

    name: Build + test (${{matrix.workflowPreset}})
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4
      - name: Install apt packages
        if: ${{ matrix.aptPackages }}
        uses: daaku/gh-action-apt-install@v4
        with:
          packages: ${{ matrix.aptPackages }}
      - uses: lukka/get-cmake@latest
      - name: Setup anew (or from cache) vcpkg (and does not build any package)
        uses: lukka/run-vcpkg@v11.5
      - name: Prepare presets
        run: cp .github/CMakeUserPresets.json CMakeUserPresets.json
        shell: bash
      - name:
          Run CMake consuming CMakePreset.json and run vcpkg to build packages
        uses: lukka/run-cmake@v10
        with:
          workflowPreset: "${{matrix.workflowPreset}}"
