name: CI
on:
  pull_request:
    paths:
      - ".github/workflows/ci.yaml"
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build-test-run:
    uses: ./.github/workflows/build-test-run.yaml
  check-clang-format:
    uses: ./.github/workflows/check-clang-format.yaml
  check-clang-tidy:
    uses: ./.github/workflows/check-clang-tidy.yaml
  check-github-actions:
    uses: nikobockerman/github-workflows/.github/workflows/check-github-actions.yaml@261e8683f0b52b7f6a9d91e2ea639a46f168ce8a
  check-prettier:
    uses: nikobockerman/github-workflows/.github/workflows/check-prettier.yaml@261e8683f0b52b7f6a9d91e2ea639a46f168ce8a
  check-renovate-config:
    uses: nikobockerman/github-workflows/.github/workflows/check-renovate-config.yaml@261e8683f0b52b7f6a9d91e2ea639a46f168ce8a
  check-shellcheck:
    uses: nikobockerman/github-workflows/.github/workflows/check-shellcheck.yaml@261e8683f0b52b7f6a9d91e2ea639a46f168ce8a
  check-yarn:
    uses: nikobockerman/github-workflows/.github/workflows/check-yarn.yaml@261e8683f0b52b7f6a9d91e2ea639a46f168ce8a

  prebuild-devcontainer:
    uses: nikobockerman/github-workflows/.github/workflows/devcontainer-cache.yaml@261e8683f0b52b7f6a9d91e2ea639a46f168ce8a
    permissions:
      contents: read
      packages: write
    with:
      cache-type: intermediate
  check-devcontainer:
    needs: prebuild-devcontainer
    uses: ./.github/workflows/check-devcontainer.yaml
