name: CI
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Run every Monday at 00:30 UTC
    - cron: "30 0 * * 1"
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build-test-run:
    uses: ./.github/workflows/build-test-run.yaml
  check-clang-format:
    uses: ./.github/workflows/check-clang-format.yaml
  check-clang-tidy:
    uses: ./.github/workflows/check-clang-tidy.yaml
  check-prettier:
    uses: nikobockerman/github-workflows/.github/workflows/check-prettier.yaml@e3c5dcaa34bc5425edf93305619726bd5e6a1cc5
  check-renovate-config:
    uses: nikobockerman/github-workflows/.github/workflows/check-renovate-config.yaml@e3c5dcaa34bc5425edf93305619726bd5e6a1cc5
  check-shellcheck:
    uses: nikobockerman/github-workflows/.github/workflows/check-shellcheck.yaml@e3c5dcaa34bc5425edf93305619726bd5e6a1cc5
  check-yarn:
    uses: nikobockerman/github-workflows/.github/workflows/check-yarn.yaml@e3c5dcaa34bc5425edf93305619726bd5e6a1cc5

  check:
    needs:
      - build-test-run
      - check-clang-format
      - check-clang-tidy
      - check-prettier
      - check-renovate-config
      - check-shellcheck
      - check-yarn
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
