name: CI
on:
  pull_request:
    paths:
      - ".github/workflows/ci.yaml"
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build-test-run:
    uses: ./.github/workflows/build-test-run.yaml
  check-clang-format:
    uses: ./.github/workflows/check-clang-format.yaml
  check-clang-tidy:
    uses: ./.github/workflows/check-clang-tidy.yaml
  check-github-actions:
    uses: nikobockerman/github-workflows/.github/workflows/check-github-actions.yaml@8cef1a279f360e3fe278d336a97e512d9f4a4306
  check-prettier:
    uses: nikobockerman/github-workflows/.github/workflows/check-prettier.yaml@8cef1a279f360e3fe278d336a97e512d9f4a4306
  check-renovate-config:
    uses: nikobockerman/github-workflows/.github/workflows/check-renovate-config.yaml@8cef1a279f360e3fe278d336a97e512d9f4a4306
  check-shellcheck:
    uses: nikobockerman/github-workflows/.github/workflows/check-shellcheck.yaml@8cef1a279f360e3fe278d336a97e512d9f4a4306
  check-yarn:
    uses: nikobockerman/github-workflows/.github/workflows/check-yarn.yaml@8cef1a279f360e3fe278d336a97e512d9f4a4306

  prebuild-devcontainer:
    uses: nikobockerman/github-workflows/.github/workflows/devcontainer-cache.yaml@89629c1b4a9d93086ea77a7eb87d7db6ce73a00e
    permissions:
      contents: read
      packages: write
    with:
      cache-type: intermediate
  check-devcontainer:
    needs: prebuild-devcontainer
    uses: ./.github/workflows/check-devcontainer.yaml
