name: CI

on:
  push:
    branches: ["main"]
  schedule:
    # Run every Monday at 00:30 UTC
    - cron: "30 0 * * 1"
  workflow_dispatch:

jobs:
  build-test-run:
    uses: ./.github/workflows/build-test-run.yaml
  check-clang-format:
    uses: ./.github/workflows/check-clang-format.yaml
  check-clang-tidy:
    uses: ./.github/workflows/check-clang-tidy.yaml
  check-github-actions:
    uses: nikobockerman/github-workflows/.github/workflows/check-github-actions.yaml@d32b3b6765f463389cf43ee69b0bb1a6a8fe80f6
  check-prettier:
    uses: nikobockerman/github-workflows/.github/workflows/check-prettier.yaml@d32b3b6765f463389cf43ee69b0bb1a6a8fe80f6
  check-renovate-config:
    uses: nikobockerman/github-workflows/.github/workflows/check-renovate-config.yaml@d32b3b6765f463389cf43ee69b0bb1a6a8fe80f6
  check-yarn:
    uses: nikobockerman/github-workflows/.github/workflows/check-yarn.yaml@d32b3b6765f463389cf43ee69b0bb1a6a8fe80f6
