name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    paths:
      - ".github/workflows/ci.yaml"
  schedule:
    # Run every Monday at 00:30 UTC
    - cron: "30 0 * * 1"
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build-test-run:
    uses: ./.github/workflows/build-test-run.yaml
  check-clang-format:
    uses: ./.github/workflows/check-clang-format.yaml
  check-clang-tidy:
    uses: ./.github/workflows/check-clang-tidy.yaml
  check-github-actions:
    uses: nikobockerman/github-workflows/.github/workflows/check-github-actions.yaml@b216e1ae8983e72a3195846d15ae28b5f35f1083
  check-prettier:
    uses: nikobockerman/github-workflows/.github/workflows/check-prettier.yaml@b216e1ae8983e72a3195846d15ae28b5f35f1083
  check-renovate-config:
    uses: nikobockerman/github-workflows/.github/workflows/check-renovate-config.yaml@b216e1ae8983e72a3195846d15ae28b5f35f1083
  check-yarn:
    uses: nikobockerman/github-workflows/.github/workflows/check-yarn.yaml@b216e1ae8983e72a3195846d15ae28b5f35f1083
