name: CI
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Run every Monday at 00:30 UTC
    - cron: "30 0 * * 1"
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build-test-run:
    uses: ./.github/workflows/build-test-run.yaml
  check-clang-format:
    uses: ./.github/workflows/check-clang-format.yaml
  check-clang-tidy:
    uses: ./.github/workflows/check-clang-tidy.yaml
  check-github-actions:
    uses: nikobockerman/github-workflows/.github/workflows/check-github-actions.yaml@2cf25ef6b41c3eb97a1e61e328bdc34dc6c9b762
  check-prettier:
    uses: nikobockerman/github-workflows/.github/workflows/check-prettier.yaml@2cf25ef6b41c3eb97a1e61e328bdc34dc6c9b762
  check-renovate-config:
    uses: nikobockerman/github-workflows/.github/workflows/check-renovate-config.yaml@2cf25ef6b41c3eb97a1e61e328bdc34dc6c9b762
  check-shellcheck:
    uses: nikobockerman/github-workflows/.github/workflows/check-shellcheck.yaml@2cf25ef6b41c3eb97a1e61e328bdc34dc6c9b762
  check-yarn:
    uses: nikobockerman/github-workflows/.github/workflows/check-yarn.yaml@2cf25ef6b41c3eb97a1e61e328bdc34dc6c9b762
