name: CI
on:
  pull_request:
    paths:
      - ".github/workflows/ci.yaml"
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build-test-run:
    uses: ./.github/workflows/build-test-run.yaml
  check-clang-format:
    uses: ./.github/workflows/check-clang-format.yaml
  check-clang-tidy:
    uses: ./.github/workflows/check-clang-tidy.yaml
  check-github-actions:
    uses: nikobockerman/github-workflows/.github/workflows/check-github-actions.yaml@88efa388aef31b038ce87b84fa64378482af888c
  check-prettier:
    uses: nikobockerman/github-workflows/.github/workflows/check-prettier.yaml@88efa388aef31b038ce87b84fa64378482af888c
  check-renovate-config:
    uses: nikobockerman/github-workflows/.github/workflows/check-renovate-config.yaml@88efa388aef31b038ce87b84fa64378482af888c
  check-shellcheck:
    uses: nikobockerman/github-workflows/.github/workflows/check-shellcheck.yaml@88efa388aef31b038ce87b84fa64378482af888c
  check-yarn:
    uses: nikobockerman/github-workflows/.github/workflows/check-yarn.yaml@88efa388aef31b038ce87b84fa64378482af888c
