name: Devcontainer
on:
  pull_request:
    paths:
      - "**.cpp"
      - "**.hpp"
      - "**/CMakeLists.txt"
      - ".devcontainer/**"
      - ".github/conan-profiles/**"
      - ".github/workflows/devcontainer.yaml"
      - "aoc/**/input-*.txt"
      - "CMakePresets.json"
      - "conan.lock"
      - "conanfile.txt"
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

env:
  IMAGE_NAME: ${{ github.repository }}-devcontainer
  REGISTRY: ghcr.io

jobs:
  prebuild:
    if:
      contains(fromJSON('["workflow_call", "workflow_dispatch"]'),
      github.event_name)
    name: Prebuild devcontainer
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 30
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Prebuild devcontainer
        uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6 # v0.3.1900000417
        with:
          imageName: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          cacheTo:
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache
          push: always

  check:
    name: Check devcontainer works
    needs:
      - prebuild
    if:
      always() && contains(fromJSON('["success", "skipped"]'),
      needs.prebuild.result)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Check devcontainer
        uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6 # v0.3.1900000417
        with:
          runCmd: |
            cmake --workflow --preset dev-clang-release && \
              ./build/clang/Release/aoc/aoc/aoc
          push: never
