name: CMake with Conan dependencies

on:
  push:
    branches: ["nikobockerman-patch-1"]
  pull_request:
    branches: ["main"]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install conan and deps
        run: |
          python -m venv venv
          . venv/Scripts/activate
          pip install conan
          conan profile detect
          conan install . -pr:h default -pr:b default -s:h build_type=${{env.BUILD_TYPE}} -s:h compiler.cppstd=23 -s:h compiler.update=5 -c:h tools.cmake.cmake_layout:build_folder_vars="['settings.compiler']" --build=missing

      - name: Configure CMake
        run: cmake --preset MSVC

      - name: Build
        run: cmake --build --preset "MSVC ${{env.BUILD_TYPE}}" -v

      - name: Test
        run: ctest --preset "MSVC ${{env.BUILD_TYPE}}"
